"""initial schema

Revision ID: d6d79cb46f27
Revises: 
Create Date: 2026-03-16 22:28:37.079955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd6d79cb46f27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=3000), nullable=True),
    sa.Column('skills', sqlmodel.sql.sqltypes.AutoString(length=3000), nullable=True),
    sa.Column('education', sqlmodel.sql.sqltypes.AutoString(length=3000), nullable=True),
    sa.Column('experience', sqlmodel.sql.sqltypes.AutoString(length=3000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_candidate_id'), 'resumes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resumes_is_active'), 'resumes', ['is_active'], unique=False)
    op.add_column('applications', sa.Column('resume_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_applications_resume_id'), 'applications', ['resume_id'], unique=False)
    op.create_foreign_key(None, 'applications', 'resumes', ['resume_id'], ['id'])
    op.add_column('candidates', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.create_index(op.f('ix_candidates_user_id'), 'candidates', ['user_id'], unique=True)
    op.create_foreign_key(None, 'candidates', 'users', ['user_id'], ['id'])
    op.drop_column('candidates', 'email')
    op.add_column('companies', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_companies_owner_id'), 'companies', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'companies', 'users', ['owner_id'], ['id'])
    op.create_index(op.f('ix_jobs_location'), 'jobs', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_location'), table_name='jobs')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_companies_owner_id'), table_name='companies')
    op.drop_column('companies', 'owner_id')
    op.add_column('candidates', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_index(op.f('ix_candidates_user_id'), table_name='candidates')
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.drop_column('candidates', 'user_id')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_applications_resume_id'), table_name='applications')
    op.drop_column('applications', 'resume_id')
    op.drop_index(op.f('ix_resumes_is_active'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_candidate_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
